on:
  push:
    tags:
      - "v*.*.*"

name: Build and Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Install Ruby
        id: install_ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Install dependencies
        id: install_dependencies
        run: |
          bundle install

      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Build
        id: build
        run: |
          gem build crisp-api.gemspec

      - name: Publish
        id: publish
        run: |
          gem push crisp-api-${{ steps.current_tag.outputs.tag }}.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
